In [11]:
import numpy as np
import matplotlib.pyplot as plt

In [9]:
road=np.zeros((road_width, road_length), dtype=int)

In [16]:
road_length=20
road_width=2
print(road)
production_prob=0.7

[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]]


In [17]:
#Production of vehicles
if np.random.random()<production_prob:
    vehicle_length = np.random.choice([1,2,5,9])
    if vehicle_length == 1:
        vehicle_width=1
    else:
        vehicle_width=2
    if road[0:vehicle_width-1, 0:vehicle_length-1] == 0:
        road[0:vehicle_width-1, 0:vehicle_length-1] = 1
    else:
        pass

[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]]
